apiVersion: v2
name: gardener-simulator
description: A Helm chart for Gardener Cluster Simulator
type: application
version: 0.3.0
appVersion: "1.2.0"
keywords:
  - gardener
  - simulator
  - kubernetes
  - testing
maintainers:
  - name: Yash Sharma
    email: yassharma@purestorage.com

