---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shoots.core.gardener.cloud
spec:
  scope: Namespaced
  names:
    kind: Shoot
    listKind: ShootList
    plural: shoots
    singular: shoot
    shortNames:
      - sh
  group: core.gardener.cloud
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true