apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gardener-simulator.fullname" . }}
  labels:
    {{- include "gardener-simulator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gardener-simulator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gardener-simulator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.simulator.port }}
              protocol: TCP
            - name: management
              containerPort: {{ add .Values.simulator.port 1 }}
              protocol: TCP
          args:
            - "--port"
            - "{{ .Values.simulator.port }}"
            - "--projects"
            - "{{ .Values.simulator.projects }}"
            - "--shoots"
            - "{{ .Values.simulator.shoots }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: management
            initialDelaySeconds: {{ .Values.healthCheck.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: management
            initialDelaySeconds: {{ .Values.healthCheck.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.readiness.periodSeconds }}
          volumeMounts:
            - name: certs
              mountPath: {{ .Values.simulator.certDir }}
      volumes:
        - name: certs
          emptyDir: {}

