apiVersion: v1
kind: Service
metadata:
  name: {{ include "gardener-simulator.fullname" . }}
  labels:
    {{- include "gardener-simulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "gardener-simulator.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      {{- if and (eq .Values.service.type "NodePort") .Values.service.apiNodePort }}
      nodePort: {{ .Values.service.apiNodePort }}
      {{- end }}
      protocol: TCP
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
      {{- if and (eq .Values.service.type "NodePort") .Values.service.managementNodePort }}
      nodePort: {{ .Values.service.managementNodePort }}
      {{- end }}
      protocol: TCP

